/*
     * * * * * * * * * * * * * * * * * * *
    *               AMMAR DIB              *
   *       Realese Date: 25 Jun 2014        *
  *          Twitter Reader System           *
   *                                        *
    *      Y!   ammarnet83@yahoo.com       *
     * * * * * * * * * * * * * * * * * * *
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TwitterReader
{
    public class AuthConfig
    {
        //generated by twitter application dev.twitter.com/apps
        public static string consumerKey = "0sZihVEwQmkSUMBVQaJD2Xu0C";
        public static string consumerSecret = "6DVwLxJIjC6n9j7jLA9QqRQrxl9ImwZLP7l3Qf24okJn3bZ3oq";
        public static string accessToken = "250055447-TSp9BMg7rk8NGKsEMsjg7Sl8UluZk9aJIlkTJOtE";
        public static string accessTokenSecret = "epc4OwpG80s5f21uMp0FtHpJrTcNJ9AsCaKiFaClBOei4";
    }
}